<?php

namespace Steodec\Controllers;

class HttpStatus {
    const Continue                        = 100;
    const Switching_Protocols             = 101;
    const Early_Hints                     = 103;
    const OK                              = 200;
    const Created                         = 201;
    const Accepted                        = 202;
    const Non_Authoritative_Information   = 203;
    const No_Content                      = 204;
    const Reset_Content                   = 205;
    const Partial_Content                 = 206;
    const Multiple_Choices                = 300;
    const Moved_Permanently               = 301;
    const Found                           = 302;
    const See_Other                       = 303;
    const Not_Modified                    = 304;
    const Temporary_Redirect              = 307;
    const Permanent_Redirect              = 308;
    const Bad_Request                     = 400;
    const Unauthorized                    = 401;
    const Payment_Required                = 402;
    const Forbidden                       = 403;
    const Not_Found                       = 404;
    const Method_Not_Allowed              = 405;
    const Not_Acceptable                  = 406;
    const Proxy_Authentication_Required   = 407;
    const Request_Timeout                 = 408;
    const Conflict                        = 409;
    const Gone                            = 410;
    const Length_Required                 = 411;
    const Precondition_Failed             = 412;
    const Payload_Too_Large               = 413;
    const URI_Too_Long                    = 414;
    const Unsupported_Media_Type          = 415;
    const Range_Not_Satisfiable           = 416;
    const Expectation_Failed              = 417;
    const teapot                          = 418;
    const Unprocessable_Entity            = 422;
    const Too_Early                       = 425;
    const Upgrade_Required                = 426;
    const Precondition_Required           = 428;
    const Too_Many_Requests               = 429;
    const Request_Header_Fields_Too_Large = 431;
    const Unavailable_For_Legal_Reasons   = 451;
    const Internal_Server_Error           = 500;
    const Not_Implemented                 = 501;
    const Bad_Gateway                     = 502;
    const Service_Unavailable             = 503;
    const Gateway_Timeout                 = 504;
    const HTTP_Version_Not_Supported      = 505;
    const Variant_Also_Negotiates         = 506;
    const Insufficient_Storage            = 507;
    const Loop_Detected                   = 508;
    const Not_Extended                    = 510;
    const Network_Authentication_Required = 511;
}